// 観察記録フォームコンポーネント
import { useState } from 'react'
import { Save, AlertCircle, Mic, Sparkles, Loader2 } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { StudentSelector } from './student-selector'
import { TagDisplay } from './tag-display'
import { VoiceRecorder } from './voice-recorder'
import { TextImprovementPanel } from './text-improvement-panel'
import type { StudentReference, Tag, ObservationType, PriorityLevel, InputMethod } from '@/types'
import { tagCategories, priorityColors } from '@/data/tag-categories'
import { analyzeObservation, generateMockAnalysis } from '@/lib/ai/tag-analyzer'
import { toast } from 'sonner'

interface ObservationFormProps {
  onSubmit: (data: ObservationFormData) => void
  isSubmitting?: boolean
}

export interface ObservationFormData {
  students: StudentReference[]
  content: {
    text: string
    audioBlob?: Blob
    audioUrl?: string
    duration?: number
  }
  type: ObservationType
  tags: Tag[]
  priority: PriorityLevel
  location?: string
  templateId?: string
  inputMethod: InputMethod
  isOfflineCreated: boolean
  teacherId: string
  aiAnalysis?: {
    sentiment: number
    keywords: string[]
    suggestedActions: string[]
    confidence: number
  }
}

export function ObservationForm({ onSubmit, isSubmitting = false }: ObservationFormProps) {
  // フォームの状態管理
  const [students, setStudents] = useState<StudentReference[]>([])
  const [contentText, setContentText] = useState('')
  const [type, setType] = useState<ObservationType>('behavioral')
  const [tags, setTags] = useState<Tag[]>([])
  const [priority, setPriority] = useState<PriorityLevel>('normal')
  const [location, setLocation] = useState('')
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [useVoiceInput, setUseVoiceInput] = useState(false)
  const [audioBlob, setAudioBlob] = useState<Blob | null>(null)

  // AI分析の状態管理
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [aiAnalysis, setAiAnalysis] = useState<ObservationFormData['aiAnalysis'] | null>(null)
  const [showAiSuggestions, setShowAiSuggestions] = useState(false)

  // テキスト改善の状態管理
  const [textImprovements, setTextImprovements] = useState<{
    original?: string
    restructured?: string
    summary?: string
  }>({})
  const [showTextImprovement, setShowTextImprovement] = useState(false)
  const [isFromVoiceInput, setIsFromVoiceInput] = useState(false)

  // 音声入力からテキストを受け取る
  const handleVoiceTranscript = async (transcript: string, blob?: Blob) => {
    console.log('音声認識結果を受信:', transcript)

    if (!transcript || !transcript.trim()) {
      console.warn('空の音声認識結果を受信')
      toast.error('音声認識結果が空です。もう一度お試しください。')
      return
    }

    setContentText(transcript)
    if (blob) {
      setAudioBlob(blob)
    }

    // エラーをクリア（特に観察内容のエラー）
    setErrors(prev => {
      const newErrors = { ...prev }
      delete newErrors.content
      return newErrors
    })

    // 音声入力後は手入力モードに戻す
    setUseVoiceInput(false)
    setIsFromVoiceInput(true)

    // 自動分析は実行せず、ユーザーがボタンを押すのを待つ
    toast.info('音声入力が完了しました。必要に応じてAI分析ボタンを押してください。')
  }

  // AI分析の実行
  const handleAiAnalysis = async (includeTextImprovement: boolean = false) => {
    if (!contentText.trim()) {
      toast.error('観察内容を入力してから分析してください')
      return
    }

    setIsAnalyzing(true)
    setShowAiSuggestions(false)
    setShowTextImprovement(false)

    try {
      // 生徒名を取得
      const studentNames = students.map(s => s.name)

      // AI分析を実行（音声入力の場合はテキスト改善も含む）
      const result = await analyzeObservation(
        contentText,
        studentNames,
        location,
        includeTextImprovement || isFromVoiceInput
      )

      if (result) {
        // 分析結果を適用
        setTags([...tags.filter(t => !t.isAutoGenerated), ...result.tags])
        setPriority(result.priority)
        setType(result.type)
        if (result.location && !location) {
          setLocation(result.location)
        }
        setAiAnalysis(result.aiAnalysis)
        setShowAiSuggestions(true)

        // テキスト改善結果を設定
        if (result.restructuredText || result.summary) {
          setTextImprovements({
            original: result.originalText || contentText,
            restructured: result.restructuredText,
            summary: result.summary
          })
          setShowTextImprovement(true)
        }

        const message = includeTextImprovement
          ? 'AI分析とテキスト改善が完了しました'
          : 'AI分析が完了しました'

        toast.success(message, {
          description: `${result.tags.length}個のタグを生成しました（信頼度: ${Math.round(result.aiAnalysis.confidence * 100)}%）`
        })
      } else {
        // APIエラーの場合はモック分析を使用
        console.warn('AI分析に失敗しました。モック分析を使用します。')
        const mockResult = generateMockAnalysis(contentText)

        setTags([...tags.filter(t => !t.isAutoGenerated), ...mockResult.tags])
        setPriority(mockResult.priority)
        setType(mockResult.type)
        setAiAnalysis(mockResult.aiAnalysis)
        setShowAiSuggestions(true)

        toast.warning('AI分析サービスに接続できませんでした', {
          description: '簡易分析を実行しました'
        })
      }
    } catch (error) {
      console.error('AI分析エラー:', error)
      toast.error('AI分析中にエラーが発生しました')
    } finally {
      setIsAnalyzing(false)
    }
  }

  // テキスト改善結果を使用
  const handleUseImprovedText = (text: string) => {
    setContentText(text)
    setShowTextImprovement(false)

    // 改善されたテキストを使用したらcontentのエラーをクリア
    if (text.trim() && errors.content) {
      setErrors(prev => {
        const newErrors = { ...prev }
        delete newErrors.content
        return newErrors
      })
    }

    toast.success('改善されたテキストを適用しました')
  }

  // バリデーション
  const validate = (): boolean => {
    const newErrors: Record<string, string> = {}

    if (students.length === 0) {
      newErrors.students = '生徒を選択してください'
    }

    if (!contentText.trim()) {
      newErrors.content = '観察内容を入力してください'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  // フォーム送信
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    if (!validate()) {
      return
    }

    const formData: ObservationFormData = {
      students,
      content: {
        text: contentText.trim(),
        audioBlob: audioBlob || undefined,
      },
      type,
      tags,
      priority,
      location: location.trim() || undefined,
      inputMethod: audioBlob ? 'voice' : 'text',
      isOfflineCreated: false,
      teacherId: 'teacher-001', // TODO: 実際の教員IDを使用
      aiAnalysis: aiAnalysis || undefined,
    }

    onSubmit(formData)
  }

  // フォームリセット
  const resetForm = () => {
    setStudents([])
    setContentText('')
    setType('behavioral')
    setTags([])
    setPriority('normal')
    setLocation('')
    setErrors({})
    setAudioBlob(null)
    setUseVoiceInput(false)
    setAiAnalysis(null)
    setShowAiSuggestions(false)
    setTextImprovements({})
    setShowTextImprovement(false)
    setIsFromVoiceInput(false)
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>新しい観察記録</CardTitle>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-6">
          {/* 生徒選択 */}
          <div>
            <StudentSelector
              selectedStudents={students}
              onStudentsChange={(newStudents) => {
                setStudents(newStudents)
                // 生徒が選択されたらstudentsのエラーをクリア
                if (newStudents.length > 0 && errors.students) {
                  setErrors(prev => {
                    const newErrors = { ...prev }
                    delete newErrors.students
                    return newErrors
                  })
                }
              }}
              multiple={true}
              required={true}
            />
            {errors.students && (
              <p className="text-sm text-red-500 mt-1 flex items-center gap-1">
                <AlertCircle className="h-3 w-3" />
                {errors.students}
              </p>
            )}
          </div>

          {/* 観察内容 */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <Label htmlFor="content">
                観察内容 <span className="text-red-500">*</span>
              </Label>
              <Button
                type="button"
                variant={useVoiceInput ? 'default' : 'outline'}
                size="sm"
                onClick={() => setUseVoiceInput(!useVoiceInput)}
              >
                <Mic className="h-4 w-4 mr-1" />
                {useVoiceInput ? '音声入力中' : '音声入力'}
              </Button>
            </div>

            {useVoiceInput ? (
              <VoiceRecorder
                onTranscriptComplete={handleVoiceTranscript}
                placeholder="観察した内容を音声で入力..."
              />
            ) : (
              <>
                <Textarea
                  id="content"
                  placeholder="観察した内容を詳しく記入してください..."
                  value={contentText}
                  onChange={(e) => {
                    setContentText(e.target.value)
                    // 入力があったらcontentのエラーをクリア
                    if (e.target.value.trim() && errors.content) {
                      setErrors(prev => {
                        const newErrors = { ...prev }
                        delete newErrors.content
                        return newErrors
                      })
                    }
                  }}
                  rows={4}
                  className="mt-1"
                  data-testid="observation-content"
                />
                {contentText && audioBlob && (
                  <p className="text-xs text-blue-600 mt-1">
                    音声入力から変換されたテキストです
                  </p>
                )}
              </>
            )}

            {errors.content && (
              <p className="text-sm text-red-500 mt-1 flex items-center gap-1">
                <AlertCircle className="h-3 w-3" />
                {errors.content}
              </p>
            )}

            {/* AI分析ボタン */}
            {contentText && (
              <div className="mt-3 space-y-2">
                <div className="flex gap-2">
                  <Button
                    type="button"
                    variant={isFromVoiceInput ? "outline" : "secondary"}
                    size="sm"
                    onClick={() => handleAiAnalysis(false)}
                    disabled={isAnalyzing}
                    data-testid="ai-analyze-btn"
                  >
                    {isAnalyzing ? (
                      <>
                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        AI分析中...
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-4 w-4 mr-2" />
                        AIで自動タグ付け
                      </>
                    )}
                  </Button>
                  <Button
                    type="button"
                    variant={isFromVoiceInput ? "secondary" : "outline"}
                    size="sm"
                    onClick={() => handleAiAnalysis(true)}
                    disabled={isAnalyzing}
                    data-testid="ai-improve-btn"
                  >
                    {isAnalyzing ? (
                      <>
                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        処理中...
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-4 w-4 mr-2" />
                        テキスト整形
                        {isFromVoiceInput && <span className="ml-1 text-xs">(推奨)</span>}
                      </>
                    )}
                  </Button>
                </div>
                {isFromVoiceInput && !showAiSuggestions && (
                  <p className="text-xs text-blue-600 flex items-center gap-1">
                    💡 音声入力の場合は「テキスト整形」で句読点や文法を自動修正できます
                  </p>
                )}
                {showAiSuggestions && aiAnalysis && (
                  <p className="text-xs text-green-600 flex items-center gap-1">
                    <Sparkles className="h-3 w-3" />
                    AI分析完了（信頼度: {Math.round(aiAnalysis.confidence * 100)}%）
                  </p>
                )}
              </div>
            )}

            {/* テキスト改善パネル */}
            {showTextImprovement && (
              <div className="mt-3">
                <TextImprovementPanel
                  originalText={textImprovements.original}
                  restructuredText={textImprovements.restructured}
                  summary={textImprovements.summary}
                  onUseText={handleUseImprovedText}
                  isVisible={showTextImprovement}
                />
              </div>
            )}
          </div>

          {/* カテゴリ選択 */}
          <div>
            <Label htmlFor="type">カテゴリ</Label>
            <select
              id="type"
              value={type}
              onChange={(e) => setType(e.target.value as ObservationType)}
              className="w-full px-3 py-2 border rounded-md mt-1"
              data-testid="observation-type"
            >
              {Object.entries(tagCategories).map(([key, info]) => (
                <option key={key} value={key}>
                  {info.icon} {info.label} - {info.description}
                </option>
              ))}
            </select>
          </div>

          {/* 優先度選択 */}
          <div>
            <Label htmlFor="priority">優先度</Label>
            <div className="flex gap-2 mt-1">
              {Object.entries(priorityColors).map(([key, info]) => (
                <button
                  key={key}
                  type="button"
                  onClick={() => setPriority(key as PriorityLevel)}
                  className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${
                    priority === key
                      ? `${info.bgColor} ${info.color} ring-2 ring-offset-2 ring-blue-500`
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                  data-testid={`priority-${key}`}
                >
                  {info.label}
                </button>
              ))}
            </div>
          </div>

          {/* 場所 */}
          <div>
            <Label htmlFor="location">場所（任意）</Label>
            <Input
              id="location"
              type="text"
              placeholder="例: 教室、廊下、体育館..."
              value={location}
              onChange={(e) => setLocation(e.target.value)}
              className="mt-1"
              data-testid="observation-location"
            />
          </div>

          {/* タグ */}
          <TagDisplay
            tags={tags}
            onTagsChange={setTags}
            allowEdit={true}
            showCategory={true}
          />

          {/* AI推奨アクション */}
          {showAiSuggestions && aiAnalysis && aiAnalysis.suggestedActions.length > 0 && (
            <div className="border-l-4 border-blue-400 bg-blue-50 p-4 rounded-r-lg">
              <div className="flex items-center gap-2 mb-2">
                <Sparkles className="h-4 w-4 text-blue-600" />
                <span className="text-sm font-medium text-blue-900">AI推奨アクション</span>
              </div>
              <ul className="space-y-1">
                {aiAnalysis.suggestedActions.map((action, index) => (
                  <li key={index} className="text-sm text-blue-700 flex items-start gap-1.5">
                    <span className="text-blue-400 mt-0.5">•</span>
                    <span>{action}</span>
                  </li>
                ))}
              </ul>
              {aiAnalysis.keywords.length > 0 && (
                <div className="mt-3 pt-3 border-t border-blue-200">
                  <p className="text-xs text-blue-600 mb-1">キーワード:</p>
                  <div className="flex flex-wrap gap-1">
                    {aiAnalysis.keywords.map((keyword, index) => (
                      <span
                        key={index}
                        className="inline-block px-2 py-0.5 text-xs bg-blue-100 text-blue-700 rounded"
                      >
                        {keyword}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* ボタン */}
          <div className="flex gap-3">
            <Button
              type="submit"
              disabled={isSubmitting}
              data-testid="save-observation"
            >
              {isSubmitting ? (
                <>
                  <span className="animate-spin mr-2">⏳</span>
                  保存中...
                </>
              ) : (
                <>
                  <Save className="h-4 w-4 mr-2" />
                  記録を保存
                </>
              )}
            </Button>
            <Button
              type="button"
              variant="outline"
              onClick={resetForm}
              disabled={isSubmitting}
            >
              リセット
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  )
}