// タグ表示・編集コンポーネント
import { useState } from 'react'
import { X, Plus, Tag as TagIcon } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import type { Tag, TagCategory } from '@/types'
import { tagCategories, getCategoryColor } from '@/data/tag-categories'
import { v4 as uuidv4 } from 'uuid'

interface TagDisplayProps {
  tags: Tag[]
  onTagsChange: (tags: Tag[]) => void
  allowEdit?: boolean
  showCategory?: boolean
}

export function TagDisplay({
  tags,
  onTagsChange,
  allowEdit = true,
  showCategory = true,
}: TagDisplayProps) {
  const [isAdding, setIsAdding] = useState(false)
  const [newTagText, setNewTagText] = useState('')
  const [selectedCategory, setSelectedCategory] = useState<TagCategory>('behavioral')

  // タグを削除
  const removeTag = (tagId: string) => {
    if (!allowEdit) return
    onTagsChange(tags.filter(tag => tag.id !== tagId))
  }

  // 新しいタグを追加
  const addTag = () => {
    if (!newTagText.trim()) return

    const newTag: Tag = {
      id: uuidv4(),
      label: newTagText.trim(),
      category: selectedCategory,
      color: getCategoryColor(selectedCategory),
      isAutoGenerated: false,
    }

    onTagsChange([...tags, newTag])
    setNewTagText('')
    setIsAdding(false)
  }

  // カテゴリ別にタグをグループ化
  const groupedTags = tags.reduce((acc, tag) => {
    if (!acc[tag.category]) {
      acc[tag.category] = []
    }
    acc[tag.category].push(tag)
    return acc
  }, {} as Record<TagCategory, Tag[]>)

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <Label className="flex items-center gap-1">
          <TagIcon className="h-4 w-4" />
          タグ
        </Label>
        {allowEdit && !isAdding && (
          <Button
            onClick={() => setIsAdding(true)}
            variant="ghost"
            size="sm"
            type="button"
          >
            <Plus className="h-4 w-4 mr-1" />
            タグを追加
          </Button>
        )}
      </div>

      {/* タグ追加フォーム */}
      {isAdding && (
        <div className="flex gap-2">
          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value as TagCategory)}
            className="px-2 py-1 text-sm border rounded-md"
          >
            {Object.entries(tagCategories).map(([key, info]) => (
              <option key={key} value={key}>
                {info.icon} {info.label}
              </option>
            ))}
          </select>
          <Input
            type="text"
            placeholder="タグ名を入力"
            value={newTagText}
            onChange={(e) => setNewTagText(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && addTag()}
            className="flex-1"
            autoFocus
          />
          <Button onClick={addTag} size="sm" type="button">
            追加
          </Button>
          <Button
            onClick={() => {
              setIsAdding(false)
              setNewTagText('')
            }}
            variant="ghost"
            size="sm"
            type="button"
          >
            <X className="h-4 w-4" />
          </Button>
        </div>
      )}

      {/* タグ表示 */}
      {tags.length > 0 ? (
        <div className="space-y-2">
          {showCategory ? (
            // カテゴリ別表示
            Object.entries(groupedTags).map(([category, categoryTags]) => {
              const categoryInfo = tagCategories[category as TagCategory]
              return (
                <div key={category} className="flex flex-wrap gap-2 items-start">
                  <span className="text-xs font-medium text-gray-600 min-w-[80px]">
                    {categoryInfo.icon} {categoryInfo.label}:
                  </span>
                  <div className="flex flex-wrap gap-1 flex-1">
                    {categoryTags.map(tag => (
                      <TagBadge
                        key={tag.id}
                        tag={tag}
                        onRemove={allowEdit ? () => removeTag(tag.id) : undefined}
                      />
                    ))}
                  </div>
                </div>
              )
            })
          ) : (
            // フラット表示
            <div className="flex flex-wrap gap-2">
              {tags.map(tag => (
                <TagBadge
                  key={tag.id}
                  tag={tag}
                  onRemove={allowEdit ? () => removeTag(tag.id) : undefined}
                />
              ))}
            </div>
          )}
        </div>
      ) : (
        <p className="text-sm text-gray-500">タグが設定されていません</p>
      )}
    </div>
  )
}

// タグバッジコンポーネント
interface TagBadgeProps {
  tag: Tag
  onRemove?: () => void
}

function TagBadge({ tag, onRemove }: TagBadgeProps) {
  const categoryInfo = tagCategories[tag.category]

  return (
    <Badge
      variant="secondary"
      className={`${categoryInfo.bgColor} ${categoryInfo.color} border-0`}
    >
      <span className="flex items-center gap-1">
        {tag.label}
        {tag.isAutoGenerated && (
          <span className="text-xs opacity-60">(AI)</span>
        )}
        {onRemove && (
          <button
            onClick={onRemove}
            className="ml-1 hover:bg-black/10 rounded p-0.5"
            type="button"
          >
            <X className="h-3 w-3" />
          </button>
        )}
      </span>
    </Badge>
  )
}