// AI タグ分析サービス
import type { Tag, ObservationType, PriorityLevel } from '@/types'
import type { TagAnalysisResponse } from './llama-api'
import { AIProviderManager } from './provider-manager'

// 分析結果の型定義
export interface AnalysisResult {
  tags: Tag[]
  priority: PriorityLevel
  type: ObservationType
  location?: string
  aiAnalysis: {
    sentiment: number
    keywords: string[]
    suggestedActions: string[]
    confidence: number
  }
}

// カテゴリラベルのマッピング（日本語表示用）
const categoryLabels: Record<ObservationType, string> = {
  behavioral: '行動',
  academic: '学習',
  health: '健康',
  family: '家庭',
  social: '社会性',
  emergency: '緊急'
}

// カテゴリごとの色定義
const categoryColors: Record<ObservationType, string> = {
  behavioral: '#ef4444', // red-500
  academic: '#3b82f6',   // blue-500
  health: '#10b981',     // emerald-500
  family: '#f59e0b',     // amber-500
  social: '#8b5cf6',     // violet-500
  emergency: '#dc2626'   // red-600
}

// 観察記録を分析してタグと分類を生成
export async function analyzeObservation(
  observationText: string,
  studentNames?: string[],
  location?: string
): Promise<AnalysisResult | null> {
  try {
    // プロバイダーマネージャーを使ってカスケード方式で分析
    const providerManager = AIProviderManager.getInstance()
    const response = await providerManager.analyzeWithFallback(
      observationText,
      studentNames,
      location
    )

    if (!response) {
      console.error('すべてのAIプロバイダーで分析に失敗しました')
      return null
    }

    // レスポンスをアプリケーション用の形式に変換
    const result: AnalysisResult = {
      tags: convertToTags(response.tags),
      priority: response.priority,
      type: response.type,
      location: response.location || location,
      aiAnalysis: {
        sentiment: response.sentiment,
        keywords: response.keywords,
        suggestedActions: response.suggestedActions,
        confidence: response.confidence
      }
    }

    return result
  } catch (error) {
    console.error('観察記録の分析エラー:', error)
    return null
  }
}

// APIレスポンスのタグをアプリケーションのTag型に変換
function convertToTags(
  apiTags: Array<{ label: string; category: ObservationType }>
): Tag[] {
  return apiTags.map((tag, index) => ({
    id: `ai-tag-${Date.now()}-${index}`,
    label: tag.label,
    category: tag.category,
    color: categoryColors[tag.category],
    isAutoGenerated: true // AI生成フラグを立てる
  }))
}

// 分析結果の検証
export function validateAnalysisResult(result: AnalysisResult): boolean {
  // 基本的な検証
  if (!result.tags || result.tags.length === 0) {
    return false
  }

  // 信頼度が低すぎる場合は警告
  if (result.aiAnalysis.confidence < 0.5) {
    console.warn('AI分析の信頼度が低いです:', result.aiAnalysis.confidence)
  }

  // カテゴリの検証
  const validCategories: ObservationType[] = ['behavioral', 'academic', 'health', 'family', 'social', 'emergency']
  if (!validCategories.includes(result.type)) {
    return false
  }

  // 優先度の検証
  const validPriorities: PriorityLevel[] = ['urgent', 'high', 'normal', 'low']
  if (!validPriorities.includes(result.priority)) {
    return false
  }

  return true
}

// デバッグ用: ダミーデータで分析結果を生成
export function generateMockAnalysis(text: string): AnalysisResult {
  // テキストから簡単な分析を行う（フォールバック用）
  const hasUrgentKeywords = /いじめ|暴力|自傷|緊急/.test(text)
  const hasSocialKeywords = /友達|友人|グループ|孤立|一人/.test(text)
  const hasAcademicKeywords = /宿題|勉強|成績|授業|テスト/.test(text)
  const hasHealthKeywords = /体調|病気|けが|痛|熱/.test(text)

  // 優先度を判定
  let priority: PriorityLevel = 'normal'
  if (hasUrgentKeywords) priority = 'urgent'
  else if (hasSocialKeywords || hasHealthKeywords) priority = 'high'

  // カテゴリを判定
  let type: ObservationType = 'behavioral'
  if (hasUrgentKeywords) type = 'emergency'
  else if (hasSocialKeywords) type = 'social'
  else if (hasAcademicKeywords) type = 'academic'
  else if (hasHealthKeywords) type = 'health'

  // タグを生成
  const tags: Tag[] = []
  if (hasUrgentKeywords) {
    tags.push({
      id: `mock-tag-${Date.now()}-1`,
      label: '要注意',
      category: 'emergency',
      color: categoryColors.emergency,
      isAutoGenerated: true
    })
  }
  if (hasSocialKeywords) {
    tags.push({
      id: `mock-tag-${Date.now()}-2`,
      label: '友人関係',
      category: 'social',
      color: categoryColors.social,
      isAutoGenerated: true
    })
  }
  if (hasAcademicKeywords) {
    tags.push({
      id: `mock-tag-${Date.now()}-3`,
      label: '学習関連',
      category: 'academic',
      color: categoryColors.academic,
      isAutoGenerated: true
    })
  }

  // タグが空の場合はデフォルトタグを追加
  if (tags.length === 0) {
    tags.push({
      id: `mock-tag-${Date.now()}-default`,
      label: '観察記録',
      category: type,
      color: categoryColors[type],
      isAutoGenerated: true
    })
  }

  return {
    tags,
    priority,
    type,
    location: undefined,
    aiAnalysis: {
      sentiment: 0.5,
      keywords: text.slice(0, 50).split(/\s+/).slice(0, 3),
      suggestedActions: ['継続観察', '記録の蓄積'],
      confidence: 0.3 // モック分析なので低い信頼度
    }
  }
}