// 観察記録の型定義

export interface ObservationRecord {
  id: string                        // UUID
  teacherId: string                 // 教員ID（将来の認証実装用）
  timestamp: number                 // Unix timestamp

  // 関連生徒
  students: StudentReference[]

  // 記録内容
  content: {
    text: string                    // 文字起こしまたは手入力テキスト
    audioBlob?: Blob               // 音声データ（オプション）
    audioUrl?: string              // IndexedDB内のBlobキー
    duration?: number              // 録音時間（秒）
  }

  // 分類・タグ
  type: ObservationType
  tags: Tag[]                      // 自動・手動タグ
  priority: PriorityLevel

  // メタデータ
  location?: string                // 場所（教室、廊下等）
  templateId?: string              // 使用したテンプレートID
  inputMethod: InputMethod
  isOfflineCreated: boolean        // オフライン時に作成されたか
  lastModified: number             // 最終更新日時

  // AI分析結果
  aiAnalysis?: {
    sentiment: number              // 感情スコア -1.0 ~ 1.0
    keywords: string[]             // 抽出キーワード
    suggestedActions: string[]     // 推奨アクション
    confidence: number             // AI信頼度 0.0 ~ 1.0
  }
}

export interface StudentReference {
  id: string
  name: string
  class: string                    // クラス名（例: "3年A組"）
  role: 'subject' | 'related' | 'witness'  // 記録における役割
}

export interface Tag {
  id: string
  label: string                    // タグ表示名
  category: TagCategory
  color: string                    // 表示色（TailwindCSS）
  isAutoGenerated: boolean         // AIによる自動生成か
}

export type TagCategory =
  | 'behavioral'                   // 行動
  | 'academic'                     // 学習
  | 'health'                       // 健康
  | 'family'                       // 家庭
  | 'social'                       // 人間関係
  | 'emergency'                    // 緊急

export type PriorityLevel = 'urgent' | 'high' | 'normal' | 'low'

export type ObservationType = TagCategory

export type InputMethod = 'voice' | 'text' | 'template'